### ISSUE TITLE
Add validation for joining ladder without user_name field

### ISSUE THREAD

**Issue by Wojtasik** [TheOneYouDontLike/Klesk#16]
When sending request without user_name field, Klesk creates matches with one player.

Command: `curl -d "text=joinladder test" http://localhost:1666`
Result: "Added: undedfined"
ladder.json: `{"player2":"patryk","winner":""},{"player2":"tarnas14","winner":""}`

**Comment by kjendrzyca** [comment]
We don't need to validate this. Slack knows what he does.
