### ISSUE TITLE
Score is set incorrectly when adding a result

### ISSUE THREAD

**Issue by kjendrzyca** [TheOneYouDontLike/Klesk#32]
When you add result with command like this:
`/klesk addresult +klesk anarki 23:18`

and in the ladder.json players are placed in a different order:

```
{ 
    matches: [ 
        {
            player1: 'anarki', player2: 'klesk' 
        }
    ]
}
```

then you get stats like this:
`[ anarki vs +klesk (23:18) on furious heights]`
but should be
`[ anarki vs +klesk (18:23) on furious heights]`

The best solution would be to fix how the score is saved, not how it is displayed.

**Comment by tarnas14** [comment]
I dunno, imo this is overkill (score is just a text)... and I'd honestly only format it correctly and let user input the score in whatever order they like (less annoying validation on input is always better)

**Comment by tarnas14** [comment]
did some magic in PR #30 - displaying score in the same order as players everywhere
